language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required

before_install:
  - sudo apt install liblz4-dev
  - export CC=aarch64-none-elf-gcc CXX=aarch64-none-elf-g++
  - export DEVKITPRO=${HOME}/devkitPro
  - export DEVKITA64=${DEVKITPRO}/devkitA64
  - mkdir ${DEVKITPRO} && mkdir ${DEVKITA64}
  - cd ${DEVKITPRO}
  - wget https://raw.githubusercontent.com/devkitPro/installer/master/perl/devkitA64update.pl && perl devkitA64update.pl
  - rm -r libnx && git clone https://github.com/switchbrew/libnx.git && cd libnx && make install
  - cd ${TRAVIS_BUILD_DIR} && pwd && ls

script:
  - make
