language: cpp

sudo: required

before_install:
  - sudo apt-get update && sudo apt-get install p7zip-full
  - export CC=aarch64-none-elf-gcc CXX=aarch64-none-elf-g++
  - export DEVKITPRO=${HOME}/devkitPro
  - export DEVKITA64=${DEVKITPRO}/devkitA64
  - mkdir ${DEVKITPRO} && mkdir ${DEVKITA64}
  - wget http://download.sourceforge.net/devkitpro/devkitA64/alpha6/devkitA64_a6-x86_64-linux.7z
  - 7z x devkitA64_a6-x86_64-linux.7z -aoa
  - cp -r ./devkitA64/* ${DEVKITA64}
  - [ -d libnx ] && rm -rf libnx
  - git clone https://github.com/switchbrew/libnx.git && cd libnx && make && make install && cd -

script:
  - make
  
after_success:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
